Server_Root: mem_web_test/apache/rikuden2
Listen_Http: 19206
Tomcat_Addr: 127.0.0.1
Tomcat_Port: 29206
Server_Name: s-rikuden2.cardnet.co.jp
Service_Name: httpd_mem_web_test_rikuden2
Ap_Name: KAIINWeb

