mv -i ./apache_mem_web_tepco/templates/robots.txt ./apache_mem_web_tepco/files/robots.txt
mv -i ./apache_mem_web_tohoku/templates/robots.txt ./apache_mem_web_tohoku/files/robots.txt
mv -i ./apache_mem_web_energia/templates/robots.txt ./apache_mem_web_energia/files/robots.txt
mv -i ./apache_mem_web_rikuden2/templates/robots.txt ./apache_mem_web_rikuden2/files/robots.txt
mv -i ./apache_mem_web_yonden/templates/robots.txt ./apache_mem_web_yonden/files/robots.txt
mv -i ./apache_mem_web_chuden/templates/robots.txt ./apache_mem_web_chuden/files/robots.txt
mv -i ./apache_mem_web_02_tepco/templates/robots.txt ./apache_mem_web_02_tepco/files/robots.txt
mv -i ./apache_mem_web_02_tohoku/templates/robots.txt ./apache_mem_web_02_tohoku/files/robots.txt
mv -i ./apache_mem_web_02_energia/templates/robots.txt ./apache_mem_web_02_energia/files/robots.txt
mv -i ./apache_mem_web_02_rikuden2/templates/robots.txt ./apache_mem_web_02_rikuden2/files/robots.txt
mv -i ./apache_mem_web_02_yonden/templates/robots.txt ./apache_mem_web_02_yonden/files/robots.txt
mv -i ./apache_mem_web_02_chuden/templates/robots.txt ./apache_mem_web_02_chuden/files/robots.txt
mv -i ./apache_mem_web_test_tepco/templates/robots.txt ./apache_mem_web_test_tepco/files/robots.txt
