Server_Root: web_edu/tomcat/chuden
Listen_Ajp: 28108
Listen_Http: 38108
Listen_Shutdown: 48108
Host_Name: localhost
Listen_Jmx: 8778
Service_Name: tomcat_web_edu_chuden
Instance_Name: kameiten_web_edu_chuden
Ap_Name: CHUDENWeb

