Server_Root: mem_web/tomcat/energia
Listen_Ajp: 29005
Listen_Http: 39005
Listen_Shutdown: 49005
Host_Name: localhost
Listen_Jmx: 8765
Service_Name: tomcat_mem_web_energia
Instance_Name: mem_web_energia

